export const BASE_URL = "https://opentable.herokuapp.com/api/";

export const RESTAURANTLIST_DATA = "RESTAURANTLIST_DATA";
export const RESTAURANTLIST_ERROR_DATA = "RESTAURANTLIST_ERROR_DATA";
export const RESTAURANTLIST_LOADING = "RESTAURANTLIST_LOADING";
export const RESTAURANTLIST_INITIAL_STATE = "RESTAURANTLIST_INITIAL_STATE";

export const COUNTRY_DATA = "COUNTRY_DATA";
export const COUNTRY_ERROR_DATA = "COUNTRY_ERROR_DATA";
export const COUNTRY_LOADING = "COUNTRY_LOADING";
export const COUNTRY_INITIAL_STATE = "COUNTRY_INITIAL_STATE";
export const COUNTRY_CHANGED = "COUNTRY_CHANGED";
